# Generated by Django 4.0.1 on 2022-10-31 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eeee'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
